services:
  inventory_service:
    build: .
    container_name: inventory_service
    depends_on:
      inventory_db:
        condition: service_healthy
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=inventory_db
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - SERVICE_NAME=${SERVICE_NAME}
    networks:
      - backend

  inventory_db:
    image: postgres:16
    container_name: inventory_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

volumes:
  postgres_data: {}

networks:
  backend:
    external: true
    name: api_gateway_backend